config/routes.rb
Recruiting::Application.routes.draw do
  
  resources :tags

  scope '(:locale)' do
    resources :companies
  
    devise_for :users
  
    resources :jobs
    
    get 'jobs/:id/:event' => 'jobs#transition', :as => 'jobs_event'
    get 'job_pdf/:id' => 'jobs#pdf', :as => 'job_pdf'
    
    resources :applications
    get 'applications/:id/:event' => 'applications#transition', :as => 'applications_event'
    get 'applications_own' => 'applications#own', :as => 'own_applications'
    
    resources :users
    
    match 'signout' => 'sessions#destroy'
  
  
  
  
  
  
  
  
  
  
    
    root :to => 'jobs#index'
  
  end

  match ':controller(/:action(/:id))(.:format)'
end

app/models/application.rb
class Application < ActiveRecord::Base
  attr_accessible :motivation, :user_id, :job_id, :cv, :motivational_letter,
                  :cv_file_name, :cv_file_size, :cv_content_type, :cv_uploaded_at,
                  :motivational_letter_file_name, :motivational_letter_file_size,
                  :motivational_letter_content_type, :motivational_letter_uploaded_at
  has_attached_file :cv
  has_attached_file :motivational_letter
  
  validates_attachment :cv, :presence => true,
  :content_type => { :content_type => ["application/pdf", "application/doc", "application/docx", "application/odf"] },
  :size => { :in => 0..1000.kilobytes }
  validates_attachment :motivational_letter, :presence => true,
  :content_type => { :content_type => ["application/pdf", "application/doc", "application/docx", "application/odf"] },
  :size => { :in => 0..1000.kilobytes }
  
  
  belongs_to :job
  belongs_to :user
  
  scope :owned, -> { where(user_id: [current_user.id]) }
  scope :draft, -> { where(state: ["created"]) }
  scope :published, -> { where(state: ["published"]) }
  scope :released, -> { where(state: ["released"]) }
  scope :rated, -> { where(state: ["recommended", "dissuaded"]) }
  scope :hired, -> { where(state: ["hired"]) }
  scope :declined, -> { where(state: ["declined"]) }
  
  state_machine :initial => :created do
    
    #after_transition :created => :published, :do => :send_ack_mail
    
    event :publish do
      transition :created => :published
    end
    
    event :release do
      transition :published => :released
    end
    
    event :recommend do
      transition :released => :recommended
    end
    
    event :dissuade do
      transition :released => :dissuaded
    end
    
    event :hire do
      transition :recommended => :hired
    end
    
    event :decline do
      transition [:dissuaded, :recommended] => :declined
    end
  end
  
  def send_ack_mail
    ApplicationMailer.acknowledgement_email(current_user, Job.find(@application.job_id)).deliver
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_locale
 
  def index
    
  end
  
  
  
  private
  
  def set_locale
    if params[:set_locale]
      redirect_to root_path(locale: params[:set_locale])
      #I18n.locale = params[:set_locale]
    elsif params[:locale]
      if I18n.available_locales.include?(params[:locale].to_sym)
        I18n.locale = params[:locale]
      else
        I18n.locale = I18n.default_locale
      end
    end
#    I18n.locale = params[:set_locale] || I18n.default_locale
  end
  
  def default_url_options
    { locale: I18n.locale }
  end
  
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  # GET /applications
  # GET /applications.json
  def index
    scope = params[:scope]
     if scope && scope != :published && can?(:modify, Application)
      @applications = Application.accessible_by(current_ability).send(scope)
    else
      @applications = Application.accessible_by(current_ability)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @applications }
    end
  end
  
  def transition
    @application = Application.find(params[:id])
    notice = ""
    event = params[:event]
    if @application.send(params[:event])
        notice = event.humanize + " was successfull."
        if event == :publish.to_s
          ApplicationMailer.acknowledgement_email(current_user, Job.find(@application.job_id)).deliver
        end
      else
        notice = event.humanize + " wasn't successful."
    end
    
    redirect_to applications_path, notice: notice
  end
  
  def own
    @applications = current_user.applications

    respond_to do |format|
      format.html { render template: "applications/index" }
      format.json { render json: @applications }
    end
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
    @application = Application.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @application }
    end
  end

  # GET /applications/new
  # GET /applications/new.json
  def new
    @application = Application.new
    @application.job_id = params['job_id'] if params['job_id']
    @application.user_id = current_user.id
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @application }
    end
  end

  # GET /applications/1/edit
  def edit
    @application = Application.find(params[:id])
  end

  # POST /applications
  # POST /applications.json
  def create
    @application = Application.new(params[:application])

    respond_to do |format|
      if @application.save
        format.html { redirect_to @application, notice: 'Application was successfully created.' }
        format.json { render json: @application, status: :created, location: @application }
      else
        format.html { render action: "new" }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  def publish
    @application = Application.find(params[:id])
    notice = ""
    if @application.send(params[:event])
        notice = "Application was successfully published."
      else
        notice = "Application can't be published."
    end
    
    redirect_to root_path, notice: notice
  end
  
  # PUT /applications/1
  # PUT /applications/1.json
  def update
    @application = Application.find(params[:id])

    respond_to do |format|
      if @application.update_attributes(params[:application])
        format.html { redirect_to @application, notice: 'Application was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application = Application.find(params[:id])
    @application.destroy

    respond_to do |format|
      format.html { redirect_to applications_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/___index.html.erb
<% if notice %>
	<p id="notice"><%= notice %></p>
<% end %>
<% if alert %>
	<p id="notice"><%= alert %></p>
<% end %>
<h1 class="well main-well header_text header_background"><%= t('helpers.Applications') %></h1>

<table class="table table-striped tablesorter">
	<thead>
	  <tr>
	    <th><%= t('helpers.User') %> <i class="icon-small icon-resize-vertical" /></th>
	    <th><%= t('.Motivation') %> <i class="icon-small icon-resize-vertical" /></th>
	    <th><%= t('helpers.Job') %> <i class="icon-small icon-resize-vertical" /></th>
	    <th></th>
	    <th></th>
		<% if can? :modify, Application %>
			<th><%= t('helpers.State') %> <i class="icon-small icon-resize-vertical" /></th>
		<% else %>
			<td></td>
	  	<% end %>
	  </tr>
	</thead>
	<tbody>
	<% @applications.each do |application| %>
	  <tr>
	    <td><%= User.find(application.user_id).email if application.user_id %></td>
	    <td><%= application.motivation %></td>
	    <td><%= Job.find(application.job_id).title if application.job_id %></td>
	    <td><%= link_to t('helpers.Show'), application, class: "btn btn-small" %></td>
	    
		<% if can? :modify, Application %>
		
		    <td><%= link_to t('helpers.Edit'), edit_application_path(application), name: "application_edit_button" , class: "btn btn-small" %></td>
	    	<td><%= t('scopes.' + application.human_state_name.humanize) %></td>
		<% else %>
			<td></td>
			<td></td>
	  	<% end %>
	
	  </tr>
	<% end %>
	</tbody>
</table>

<br />

<% if can? :modify, Job %>
	<%= link_to t('.New_application'), new_application_path, class: "btn btn-small" %>
<% end %>

app/views/applications/_form.html.erb
<%= form_for(@application, :html => { :multipart => true }, :validate => true) do |f| %>
  <% if @application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@application.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
      <% @application.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= t('helpers.Job') + ": " + Job.find(@application.job_id).title if @application.job_id %>
  </div>
  <div class="field">
    <%= t('applications.index.Motivation') %><br />
    <%= f.text_field :motivation %>
  </div>
  <div class="field">
    <%= t('applications.index.motivational_letter') %><br />
	  <%= f.file_field :motivational_letter %>
    <%= @application.motivational_letter_file_name unless nil %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, value: @application.user_id %>
  </div>
  <div class="field">
    <%= f.hidden_field :job_id, value: @application.job_id if @application.job_id %>
  </div>
  
  <div class="field">
    <%= t('applications.index.cv') %><br />
	  <%= f.file_field :cv %>
    <%= @application.cv_file_name unless nil %>
  </div>
  
  <div class="actions">
    <%= f.submit t("helpers.Save"), id: "save_button", class: "btn btn-small" if current_user.id == @application.user_id %>
  </div>
<% end %>

app/views/applications/edit.html.erb
<h1><%= t(".Editing_application") %></h1>

<%= render 'form' %>

<%= link_to t('helpers.Show'), @application, class: "btn btn-small" %>
<%= link_to t('helpers.Back'), applications_path, class: "btn btn-small" if can? :modify, Application %>

app/views/applications/index.html.erb
<% if notice %>
	<p id="notice"><%= notice %></p>
<% end %>
<% if alert %>
	<p id="notice"><%= alert %></p>
<% end %>
<h1 class="well main-well header_text header_background"><%= t('helpers.Applications') %></h1>

<table class="table table-striped tablesorter">
	<thead>
	  <tr>
	    <th><%= t('helpers.User') %> <i class="icon-small icon-resize-vertical" /></th>
	    <th><%= t('.Motivation') %> <i class="icon-small icon-resize-vertical" /></th>
	    <th><%= t('helpers.Job') %> <i class="icon-small icon-resize-vertical" /></th>
	    <th></th>
	    <th></th>
		<% if can? :modify, Application %>
			<th><%= t('helpers.State') %> <i class="icon-small icon-resize-vertical" /></th>
		<% else %>
			<td></td>
	  	<% end %>
	  </tr>
	</thead>
	<tbody>
	<% @applications.each do |application| %>
	  <tr>
	    <td><%= User.find(application.user_id).email if application.user_id %></td>
	    <td><%= application.motivation %></td>
	    <td><%= Job.find(application.job_id).title if application.job_id %></td>
	    <td><%= link_to t('helpers.Show'), application, class: "btn btn-small" %></td>
	    
		<% if can? :modify, Application %>
		
		    <td><%= link_to t('helpers.Edit'), edit_application_path(application), name: "application_edit_button" , class: "btn btn-small" %></td>
	    	<td><%= t('scopes.' + application.human_state_name.humanize) %></td>
		<% else %>
			<td></td>
			<td></td>
	  	<% end %>
	
	  </tr>
	<% end %>
	</tbody>
</table>

<br />

<% if can? :modify, Job %>
	<%= link_to t('.New_application'), new_application_path, class: "btn btn-small" %>
<% end %>

app/views/applications/index.html.haml
- if notice
	%p#notice= notice
- if alert
	%p#notice= alert
%h1.well.main-well.header_text.header_background= t('helpers.Applications')

%table.table.table-striped.tablesorter
	%thead
		%tr
			%th
				= t('helpers.User')
			%th
				= t('.Motivation')
			%th
				= t('helpers.Job')
			%th
			%th
			- if can? :modify, Application
				%th
					= t('helpers.State')
			- else
				%th
	%tbody
	- @applications.each do |application|
		%tr
			%td= User.find(application.user_id).email if application.user_id
			%td= application.motivation
			%td= Job.find(application.job_id).title if application.job_id
			%td= link_to t('helpers.Show'), application, class: "btn btn-small"
			- if can? :modify, Application	
				%td= link_to t('helpers.Edit'), edit_application_path(application), name: "application_edit_button" , class: "btn btn-small"
				%td= t('scopes.' + application.human_state_name.humanize)
			- else
				%td
				%td

%br

- if can? :modify, Job
	= link_to t('.New_application'), new_application_path, class: "btn btn-small"

app/views/applications/new.html.erb
<h1><%= t('applications.index.New_application') %></h1>

<%= render 'form' %>

<%= link_to t('helpers.Back'), applications_path, class: "btn btn-small" %>

app/views/applications/show.html.erb
<% if notice %>
	<p id="notice"><%= notice %></p>
<% end %>


<dl class="dl-horizontal">
  <dt>
  	<b class="label"><%= t('helpers.User') %></b>
  </dt>
  <dd style="font-size: 20px;">
  	<%= User.find(@application.user_id).email %>
  </dd>
  <dt>
  	<b class="label"><%= t('helpers.CV') %></b>
  </dt>
  <dd>
  	<%= @application.cv_file_name %>
  </dd>
  <dt>
  	<b class="label"><%= t('applications.index.Motivation') %></b>
  </dt>
  <dd>
  	<%= @application.motivation %>
  </dd>
  <dt>
  	<b class="label"><%= t('applications.index.Motivational_letter') %></b>
  </dt>
  <dd>
  	<%= @application.motivational_letter_file_name %>
  </dd>
  <dt>
  	<b class="label"><%= t('helpers.Job') %></b>
  </dt>
  <dd>
  	<%= @application.job.title if @application.job %>
  </dd>
</dl>
<% @application.state_events.each do |event| %>
	<%= link_to t("helpers." + event.to_s), applications_event_path(@application.id, event), id: event.to_s + "_button" , class: "btn btn-small" if can?(event.to_sym, Application) %>
<% end %>
<% if (@application.user.id == current_user.id || can?(:modify, Application)) %>

	<%= link_to t('helpers.Edit'), edit_application_path(@application), class: "btn btn-small" %>
<% end %>
<!-- <%= link_to t("helpers.Apply"), applications_event_path(@application.id, "publish"), class: "btn btn-small", :id => "publish_button" %> -->
<%= link_to t('helpers.Back'), applications_path, class: "btn btn-small" %>