config/routes.rb
Recruiting::Application.routes.draw do
  
  resources :tags

  scope '(:locale)' do
    resources :companies
  
    devise_for :users
  
    resources :jobs
    
    get 'jobs/:id/:event' => 'jobs#transition', :as => 'jobs_event'
    get 'job_pdf/:id' => 'jobs#pdf', :as => 'job_pdf'
    
    resources :applications
    get 'applications/:id/:event' => 'applications#transition', :as => 'applications_event'
    get 'applications_own' => 'applications#own', :as => 'own_applications'
    
    resources :users
    
    match 'signout' => 'sessions#destroy'
  
  
  
  
  
  
  
  
  
  
    
    root :to => 'jobs#index'
  
  end

  match ':controller(/:action(/:id))(.:format)'
end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :description, :title, :tasks, :qualifications, :company_id, :company, :contact_id, :contact, :state, :tag_ids, :tags, :applications
  belongs_to :company
  belongs_to :user
  has_many :applications
  has_and_belongs_to_many :tags
  accepts_nested_attributes_for :tags
  
  scope :reviewed, -> { where(state: ["reviewed", "review_requested"]) }
  scope :draft, -> { where(state: ["created"]) }
  scope :published, -> { where(state: ["published"]) }
  
  validates :contact_id, :company_id, :presence => true
  
  state_machine :initial => :created do
    
    before_transition :created => :published, :do => :print_published
    
    event :request_review do
      transition :created => :review_requested
    end
    
    event :review do
      transition :review_requested => :reviewed
    end
    
    event :publish do
      transition :reviewed => :published
    end
    
  end
  
  def print_published
    puts "publiiiiiiiiiiished"
  end
  
  
  def contact
    if contact_id
      User.find(contact_id)
    else
      User.find(Company.find(company_id).contact_id) if company_id
    end 
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  skip_before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /jobs
  # GET /jobs.json
  def index
    # if scope is given, we have to check if the user may see other publications than published ones
    scope = params[:scope]
    if scope && scope != :published && can?(:modify, Job)
      @jobs = Job.accessible_by(current_ability).send(scope)
    else
      @jobs = Job.accessible_by(current_ability)
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job }
    end
  end
  
  def pdf
    @job = Job.find(params[:id])
    
    html = render_to_string(:action => "template.html.erb", :layout => false)
    kit = PDFKit.new(html)
    kit.stylesheets << "#{Rails.root}/app/assets/stylesheets/bootstrap_and_overrides.css"
    kit.stylesheets << "#{Rails.root}/app/assets/stylesheets/bootstrap.min.css"
    send_data(kit.to_pdf, :filename => 'job.pdf', :type => 'application/pdf', :disposition => 'inline')
    
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @job = Job.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(params[:job])

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def transition
    notice = ""
    event = params[:event]
    if @job.send(params[:event])
        notice = event.humanize + " was successfull."
      else
        notice = event.humanize + " wasn't successful."
    end
    
    redirect_to root_path, notice: notice
  end
  
  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_____form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= t('helpers.Title') %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= t('helpers.State') %><br />
    <%= f.text_field :state, :value => @job.human_state_name.humanize, :disabled => true %>
  </div>
  <div class="field">
    <%= t('helpers.Description') %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= t('.Tasks') %><br />
    <%= f.text_area :tasks %>
  </div>
  <div class="field">
    <%= t('.Qualifications') %><br />
    <%= f.text_area :qualifications %>
  </div>
  
  <div class="field">
    <%= t('helpers.Contact') %><br />
    
  	<%= collection_select(:job, :contact_id, User.all, :id, :email, {include_blank: true}) %>
  </div>
  <div class="field">
    <%= t('helpers.Company') %><br />
    
  	<%= collection_select(:job, :company_id, Company.all, :id, :name) %>
  </div>
  
  <div class="actions">
    <%= f.submit t("helpers.Submit"), class: "btn btn-small", :id => "submit_button" %>
  </div>
<% end %>

app/views/jobs/_____index.html.erb
<% if notice %>
	<p id="notice"><%= notice %></p>
<% end %>
<% if alert %>
	<p id="notice"><%= alert %></p>
<% end %>
<h1 class="well main-well header_text header_background capybara-jobs"><%= t('helpers.Jobs') %></h1>


<table class="table table-striped tablesorter">
	<thead>
	  <tr>
	    <th><%= t('helpers.Title') %> <i class="icon-small icon-resize-vertical" /></th>
	    <th><%= t('helpers.Description') %> <i class="icon-small icon-resize-vertical" /></th>
	    <th><%= t('helpers.Company') %> <i class="icon-small icon-resize-vertical" /></th>
	    <th><%= t('helpers.Contact') %> <i class="icon-small icon-resize-vertical" /></th>
	    <th></th>
	    <th></th>
	    <th></th>
		<% if can? :modify, Job %>
	    	<th><%= t('helpers.State') %> <i class="icon-small icon-resize-vertical" /></th>
		<% else %>
			<th></th>
		<% end %>
	    <th></th>
	  </tr>
	</thead>
	<tbody>
	<% @jobs.each do |job| %>
	  <tr>
	    <td><%= job.title %></td>
	    <td><%= job.description %></td>
	    <%
	    	company = Company.find(job.company_id) if job.company_id
	    	contact = job.contact
	     %>
	    <td><%= link_to company.name, company, :name => "link_to_company" if job.company_id %></td>
	    <td><%= link_to "#{contact.email[0, 15]}..." if contact %></td>
	    <td><%= link_to t('helpers.Show'), job, class: "btn btn-small" if can? :modify, Job %></td>
		    
		<% if can? :modify, Job %>
		
			<td><%= link_to t('helpers.Edit'), edit_job_path(job), name: "job_edit_button" , class: "btn btn-small" %></td>
		    <td><%= link_to t('helpers.Destroy'), job, method: :delete, name: "job_destroy_button", class: "btn btn-small", data: { confirm: 'Are you sure?' } %></td>
	    	<td><%= t('scopes.' + job.state) %></td>
		<% else %>
			<td></td>
			<td></td>
			<td><%= t('scopes.' + job.state) %></td>
		<% end %>
		
		<td>
	  		<%= link_to t('helpers.Details'), job, class: "btn btn-small" %>
	  	</td>
	
	  </tr>
	<% end %>
	</tbody>
</table>

<br />

<% if can? :modify, Job %>
	<%= link_to t('helpers.New'), new_job_path, class: "btn btn-small", :id => "new_job_button" %>
<% end %>

app/views/jobs/_form.html.erb
<%= semantic_form_for @job, :validate => true do |f| %>
	<%= f.inputs :title, :description, :tasks, :qualifications %>
	<%= f.input :contact_id, :as => :select, :collection => User.all, :member_label => :email, :required => true, :input_html => { :class => 'field' } %>
	<%= f.input :company, :as => :select, :collection => Company.all, :member_label => :name, :required => true, :input_html => { :class => 'field' } %>
	<%= f.input :tags, :as => :check_boxes, :collection => Tag.all %>
	<!-- <%= f.action :submit, :label => t("helpers.Submit"), :button_html => { :class => "btn btn-small" } %> -->
	
  <div class="actions">
    <%= f.submit t("helpers.Save"), id: "save_button", id: "submit_button", class: "btn btn-small", style: "width:100px; color: rgb(51, 51, 51);" %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1><%= t('.Edit_job') %></h1>

<%= render 'form' %>

<%= link_to t('helpers.Back'), jobs_path, class: "btn btn-small" %>

app/views/jobs/index.html.erb
<% if notice %>
	<p id="notice"><%= notice %></p>
<% end %>
<% if alert %>
	<p id="notice"><%= alert %></p>
<% end %>
<h1 class="well main-well header_text header_background capybara-jobs"><%= t('helpers.Jobs') %></h1>


<table class="table table-striped tablesorter">
	<thead>
	  <tr>
	    <th><%= t('helpers.Title') %> <i class="icon-small icon-resize-vertical" /></th>
	    <th><%= t('helpers.Description') %> <i class="icon-small icon-resize-vertical" /></th>
	    <th><%= t('helpers.Company') %> <i class="icon-small icon-resize-vertical" /></th>
	    <th><%= t('helpers.Contact') %> <i class="icon-small icon-resize-vertical" /></th>
	    <th></th>
	    <th></th>
	    <th></th>
		<% if can? :modify, Job %>
	    	<th><%= t('helpers.State') %> <i class="icon-small icon-resize-vertical" /></th>
		<% else %>
			<th></th>
		<% end %>
	    <th></th>
	  </tr>
	</thead>
	<tbody>
	<% @jobs.each do |job| %>
	  <tr>
	    <td><%= job.title %></td>
	    <td><%= job.description %></td>
	    <%
	    	company = Company.find(job.company_id) if job.company_id
	    	contact = job.contact
	     %>
	    <td><%= link_to company.name, company, :name => "link_to_company" if job.company_id %></td>
	    <td><%= link_to "#{contact.email[0, 15]}..." if contact %></td>
	    <td><%= link_to t('helpers.Show'), job, class: "btn btn-small" if can? :modify, Job %></td>
		    
		<% if can? :modify, Job %>
		
			<td><%= link_to t('helpers.Edit'), edit_job_path(job), name: "job_edit_button" , class: "btn btn-small" %></td>
		    <td><%= link_to t('helpers.Destroy'), job, method: :delete, name: "job_destroy_button", class: "btn btn-small", data: { confirm: 'Are you sure?' } %></td>
	    	<td><%= t('scopes.' + job.state) %></td>
		<% else %>
			<td></td>
			<td></td>
			<td><%= t('scopes.' + job.state) %></td>
		<% end %>
		
		<td>
	  		<%= link_to t('helpers.Details'), job, class: "btn btn-small" %>
	  	</td>
	
	  </tr>
	<% end %>
	</tbody>
</table>

<br />

<% if can? :modify, Job %>
	<%= link_to t('helpers.New'), new_job_path, class: "btn btn-small", :id => "new_job_button" %>
<% end %>

app/views/jobs/index.html.slim
- if notice
	p id="notice"
		= notice
- if alert
	p id="notice"
	= alert
h1 class="well main-well header_text header_background capybara-jobs"
	= t('helpers.Jobs')


table class="table table-striped tablesorter"
	thead
	  tr
	    th
			= t('helpers.Title')
	    th
	    	= t('helpers.Description')
	    th
	    	= t('helpers.Company')
		th
			= t('helpers.Contact')
	    th
	    th
	    th
		- if can?(:modify, Job)
	    	th
	    	= t('helpers.State')
		- else
			th
	    th
	tbody
	- @jobs.each do |job|
		- company = Company.find(job.company_id) if job.company_id
		- contact = job.contact
		tr
		    td
		    	= job.title
		    td
		    	= job.description
		    td
		    	= link_to company.name, company, :name => "link_to_company" if job.company_id
		    td
		    	= link_to "#{contact.email[0, 15]}..." if contact
		    td
		    	= link_to t('helpers.Show'), job, class: "btn btn-small" if can? :modify, Job
			    
			- if can? :modify, Job
			
				td
					= link_to t('helpers.Edit'), edit_job_path(job), name: "job_edit_button" , class: "btn btn-small"
			    td
			    	= link_to t('helpers.Destroy'), job, method: :delete, name: "job_destroy_button", class: "btn btn-small", data: { confirm: 'Are you sure?' }
		    	td
		    		= t('scopes.' + job.state)
			- else
				td
				td
				td
					= t('scopes.' + job.state)
			td
		  		= link_to t('helpers.Details'), job, class: "btn btn-small"
	
br/

-if can? :modify, Job
	= link_to t('helpers.New'), new_job_path, class: "btn btn-small", :id => "new_job_button"

app/views/jobs/new.html.erb
<h1><%= t('.New_job') %></h1>

<%= render 'form' %>

<%= link_to t('helpers.Back'), jobs_path, class: "btn btn-small" %>

app/views/jobs/show.html.erb
<% if notice %>
	<p id="notice"><%= notice %></p>
<% end %>

<dl class="dl-horizontal">
  <dt>
  	<b class="label"><%= t('helpers.Title') %></b>
  </dt>
  <dd style="font-size: 20px;">
	<%= @job.title %>
  </dd>
  
  <dt>
  	<b class="label"><%= t('helpers.Description') %></b>
  </dt>
  <dd>
  	<%= @job.description %>
  </dd>
  <dt>
  	<b class="label"><%= t('jobs.form.Tasks') %></b>
  </dt>
  <dd>
  	<%= @job.tasks.html_safe if @job.tasks %>
  </dd>
  <dt>
  	<b class="label"><%= t('jobs.form.Qualifications') %></b>
  </dt>
  <dd>
  	<%= @job.qualifications.html_safe if @job.qualifications %>
  </dd>
  <dt>
  	<b class="label"><%= t('jobs.form.Tags') %></b>
  </dt>
  <dd>
  	<ul>
	  	<% @job.tags.each do |tag| %>
			<li><%= tag.name %></li>  		
	  	<% end %>
  	</ul>
  </dd>
  <% if can? :manage, Job %>
	  <dt>
	  	<b class="label"><%= t('helpers.State') %></b>
	  </dt>
	  <dd>
	  	<%= @job.state %>
	  </dd>
	<% end %>

</dl>
<% @job.state_events.each do |event| %>
	<%= link_to t("helpers." + event.to_s), jobs_event_path(@job.id, event), class: "btn btn-small", :id => event.to_s + "_button" %>
<% end %>


	<%= link_to t('helpers.Edit'), edit_job_path(@job), class: "btn btn-small" if can? :modify, Job %>
	<%= link_to t('helpers.Back'), jobs_path, class: "btn btn-small" %>
<% if user_signed_in? %>

	<%= link_to t('helpers.Apply'), new_application_path(job_id: @job.id), id: "apply_button", class: "btn btn-small" if can? :apply, Job %>
<% else %>
	
  	<%= link_to( t('helpers.Login_to_ Apply'), new_user_session_path, id: "apply_button", class: "btn btn-small") if can? :apply, Job %>
<% end %>	

  <%= link_to( t('helpers.PDF'), job_pdf_path(@job.id), id: "pdf_button", class: "btn btn-small") %>
  	

app/views/jobs/template.html.erb
<%
	@company = Company.find(@job.company_id)
%>
<div class="well">
	<h1 class="well main-well header_text header_background">
		<%= @job.title %>
	</h1>
	<div class="well main-well">
		<p style="font-size: 8pt">
			<%= @company.template_header%>
		</p>
		<br />
		<dl class="dl-horizontal">
		  
		  <dt style="width:100px;">
		  	<b class="label"><%= t('helpers.Description') %></b>
		  </dt>
		  <dd style="margin-left:110px; font-size: 8pt;">
		  	<%= @job.description %>
		  </dd>
		  <dt style="width:100px;">
		  	<b class="label"><%= t('jobs.form.Tasks') %></b>
		  </dt>
		  <dd style="margin-left:110px; font-size: 8pt;">
		  	<%= @job.tasks.html_safe if @job.tasks %>
		  </dd>
		  <dt style="width:100px;">
		  	<b class="label"><%= t('jobs.form.Qualifications') %></b>
		  </dt>
		  <dd style="margin-left:110px; font-size: 8pt;">
		  	<%= @job.qualifications.html_safe if @job.qualifications %>
		  </dd>
		</dl>
		<br />
		<p style="font-size: 8pt">
			<%= @company.template_footer %>
		</p>
		<br />
		<p>
			<%= @company.name %>, <%= @company.address %>
		</p>
		<p class="pull-right">
			<%= @job.contact.email %>
		</p>
	</div>
</div>