config/routes.rb
Recruiting::Application.routes.draw do
  
  resources :tags

  scope '(:locale)' do
    resources :companies
  
    devise_for :users
  
    resources :jobs
    
    get 'jobs/:id/:event' => 'jobs#transition', :as => 'jobs_event'
    get 'job_pdf/:id' => 'jobs#pdf', :as => 'job_pdf'
    
    resources :applications
    get 'applications/:id/:event' => 'applications#transition', :as => 'applications_event'
    get 'applications_own' => 'applications#own', :as => 'own_applications'
    
    resources :users
    
    match 'signout' => 'sessions#destroy'
  
  
  
  
  
  
  
  
  
  
    
    root :to => 'jobs#index'
  
  end

  match ':controller(/:action(/:id))(.:format)'
end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :name, :street, :zip, :city, :contact_id, :template_footer, :template_header, :contact
  has_one :user
  has_many :jobs
  
  def address
    if street != "" && street != nil
      "#{street}, #{zip} #{city}"
    elsif zip != "" && zip != nil && city != "" && city != nil
      "#{zip} #{city}"
    else
      ""
    end
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  load_and_authorize_resource
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= t('helpers.Name') %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= t('helpers.Street') %><br />
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= t('helpers.Zip') %><br />
    <%= f.number_field :zip %>
  </div>
  <div class="field">
    <%= t('helpers.City') %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= t('helpers.Contact') %><br />
    
  	<%= collection_select(:company, :contact_id, User.all, :id, :email) %>
  </div>
  <div class="field">
    <%= t('.template_header') %><br />
    <%= f.text_area :template_header, :cols => "100", :rows => "10" %>
  </div>
  <div class="field">
    <%= t('.template_footer') %><br />
    <%= f.text_area :template_footer, :cols => "100", :rows => "10" %>
  </div>
  <div class="actions">
    <%= f.submit t("helpers.Submit"), class: "btn btn-small" %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1><%= t(".Editing_company") %></h1>

<%= render 'form' %>

<%= link_to t('helpers.Show'), @company, class: "btn btn-small" %>
<%= link_to t('helpers.Back'), companies_path, class: "btn btn-small" if can? :modify, Company %>

app/views/companies/index.html.erb
<% if notice %>
	<p id="notice"><%= notice %></p>
<% end %>
<% if alert %>
	<p id="notice"><%= alert %></p>
<% end %>
<h1 class="well main-well header_text header_background"><%= t('helpers.Companies') %></h1>

<table class="table table-striped tablesorter">
	<thead>
	  <tr>
	    <th><%= t('helpers.Name') %> <i class="icon-small icon-resize-vertical" /></th>
	    <th><%= t('helpers.Address') %> <i class="icon-small icon-resize-vertical" /></th>
	    <th><%= t('.Jobs_offered') %> <i class="icon-small icon-resize-vertical" /></th>
	    <th></th>
	    <th></th>
	    <th></th>
	  </tr>
	</thead>
	<tbody>
	<% @companies.each do |company| %>
	  <tr>
	    <td><%= company.name %></td>
	    <td><%= company.address %></td>
	    <td><%= company.jobs.size %></td>
		
	    <td><%= link_to t('helpers.Show'), company, class: "btn btn-small" %></td>
	    
		<% if can? :modify, Job %>
		
	    <td><%= link_to t('helpers.Edit'), edit_company_path(company), class: "btn btn-small"%></td>
	    <td><%= link_to t('helpers.Destroy'), company, method: :delete, class: "btn btn-small", data: { confirm: 'Are you sure?' } %></td>
	  
		<% else %>
			<td></td>
			<td></td>
	  	<% end %>
	  	
	  </tr>
	<% end %>
	</tbody>
</table>

<br />

<%= link_to t('helpers.New'), new_company_path, class: "btn btn-small" %>

app/views/companies/new.html.erb
<h1><%= t('.New_company') %></h1>

<%= render 'form' %>

<%= link_to t('helpers.Back'), companies_path %>

app/views/companies/show.html.erb
<% if notice %>
	<p id="notice"><%= notice %></p>
<% end %>
<dl class="dl-horizontal">
  <dt>
  	<b class="label"><%= t('helpers.Name') %></b>
  </dt>
  <dd style="font-size: 20px;">
  <%= @company.name %>
  </dd>
  <dt>
  	<b class="label"><%= t('helpers.Street') %></b>
  </dt>
  <dd>
  <%= @company.street %>
  </dd>
  <dt>
  	<b class="label"><%= t('helpers.Zip') %></b>
  </dt>
  <dd>
  <%= @company.zip %>
  </dd>
  <dt>
  	<b class="label"><%= t('helpers.City') %></b>
  </dt>
  <dd>
  <%= @company.city %>
  </dd>
  <dt>
  	<b class="label"><%= t('helpers.Address') %></b>
  </dt>
  <dd>
  <%= @company.address %>
  </dd>
  
  <dt>
  	<b class="label"><%= t('companies.form.template_header') %></b>
  </dt>
  <dd>
  	<%= @company.template_header %>
  </dd>
  
  <dt>
  	<b class="label"><%= t('companies.form.template_footer') %></b>
  </dt>
  <dd>
  	<%= @company.template_footer %>
  </dd>

</dl>

<%= link_to t('helpers.Edit'), edit_company_path(@company), class: "btn btn-small" if can? :modify, Company %>
<%= link_to t('helpers.Back'), companies_path, class: "btn btn-small" %>