config/routes.rb
Recruiting::Application.routes.draw do
  
  resources :tags

  scope '(:locale)' do
    resources :companies
  
    devise_for :users
  
    resources :jobs
    
    get 'jobs/:id/:event' => 'jobs#transition', :as => 'jobs_event'
    get 'job_pdf/:id' => 'jobs#pdf', :as => 'job_pdf'
    
    resources :applications
    get 'applications/:id/:event' => 'applications#transition', :as => 'applications_event'
    get 'applications_own' => 'applications#own', :as => 'own_applications'
    
    resources :users
    
    match 'signout' => 'sessions#destroy'
  
  
  
  
  
  
  
  
  
  
    
    root :to => 'jobs#index'
  
  end

  match ':controller(/:action(/:id))(.:format)'
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name
  has_and_belongs_to_many :jobs
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.json
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render json: @tag, status: :created, location: @tag }
      else
        format.html { render action: "new" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.json
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= semantic_form_for @tag do |f| %>
  <%= f.inputs do %>
    <%= f.input :name %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Listing tags</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tags.each do |tag| %>
  <tr>
    <td><%= tag.name %></td>
    <td><%= link_to 'Show', tag %></td>
    <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
    <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tag.name %>
</p>


<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>